//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPazar
    {
        public int PazarId { get; set; }
        public string PazarAdi { get; set; }
        public string PazarTuru { get; set; }
        public string PazarYeri { get; set; }
    }
}
