//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        public int UrunId { get; set; }
        public Nullable<int> UrunPazariId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKategorisi { get; set; }
        public Nullable<double> UrunFiyati { get; set; }
    }
}
