//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKullaniciRol
    {
        public int RolId { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Raporlama { get; set; }
        public Nullable<bool> Tahsilat { get; set; }
        public Nullable<bool> Siparis { get; set; }
        public Nullable<bool> Ayarlar { get; set; }
        public Nullable<bool> Yetkili { get; set; }
    
        public virtual TblKullanici TblKullanici { get; set; }
    }
}
