//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblKupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblKupon()
        {
            this.TblSepetDetay = new HashSet<TblSepetDetay>();
        }
    
        public int KuponId { get; set; }
        public string KuponKodu { get; set; }
        public System.DateTime BaslangicTarihi { get; set; }
        public System.DateTime BitisTarihi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<int> MaksimumYararlanmaSayisi { get; set; }
        public Nullable<double> IndirimOrani { get; set; }
        public Nullable<double> IndirimliFiyat { get; set; }
        public Nullable<double> MinimumAlisverisTutari { get; set; }
        public string Urun { get; set; }
        public string Sepet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSepetDetay> TblSepetDetay { get; set; }
    }
}
