//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOdemeTipleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOdemeTipleri()
        {
            this.TblSepet = new HashSet<TblSepet>();
        }
    
        public int OdemeTipiId { get; set; }
        public string OdemeTipiAdi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<double> MinimumLimit { get; set; }
        public Nullable<double> MaksimumLimit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSepet> TblSepet { get; set; }
    }
}
