//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPazar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblPazar()
        {
            this.TblUrunPazar = new HashSet<TblUrunPazar>();
        }
    
        public int PazarId { get; set; }
        public string PazarAdi { get; set; }
        public string PazarTuru { get; set; }
        public string PazarYeri { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Pasif { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunPazar> TblUrunPazar { get; set; }
    }
}
