//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunHareketleri
    {
        public int HareketId { get; set; }
        public int UrunId { get; set; }
        public Nullable<int> KisiId { get; set; }
        public Nullable<int> DurumId { get; set; }
        public int DovizId { get; set; }
        public Nullable<int> UyeId { get; set; }
        public int HareketTipiId { get; set; }
        public int BirimTipiId { get; set; }
        public System.DateTime HareketTarihi { get; set; }
        public double Miktar { get; set; }
        public double BirimFiyati { get; set; }
        public Nullable<decimal> DovizKuru { get; set; }
    
        public virtual TblTeslimatDurumlari TblTeslimatDurumlari { get; set; }
        public virtual TblUrun TblUrun { get; set; }
    }
}
