//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunFiyat
    {
        public int FiyatId { get; set; }
        public int UrunId { get; set; }
        public int DovizId { get; set; }
        public double Fiyat { get; set; }
        public Nullable<bool> Indirim { get; set; }
        public int KdvOrani { get; set; }
    
        public virtual TblDoviz TblDoviz { get; set; }
        public virtual TblUrun TblUrun { get; set; }
    }
}
