//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUrun()
        {
            this.TblOrderLines = new HashSet<TblOrderLines>();
            this.TblUrunFiyat = new HashSet<TblUrunFiyat>();
            this.TblUrunHareketleri = new HashSet<TblUrunHareketleri>();
            this.TblUrunKategori = new HashSet<TblUrunKategori>();
            this.TblUrunPazar = new HashSet<TblUrunPazar>();
            this.TblUrunStock = new HashSet<TblUrunStock>();
        }
    
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public string UrunKategorisi { get; set; }
        public Nullable<double> UrunFiyati { get; set; }
        public string img { get; set; }
        public Nullable<int> StokAdedi { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> UrunNo { get; set; }
        public Nullable<bool> IsExist { get; set; }
        public Nullable<bool> IsAtDiscount { get; set; }
        public string Yol { get; set; }
        public Nullable<int> KategoriId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderLines> TblOrderLines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunFiyat> TblUrunFiyat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunHareketleri> TblUrunHareketleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunKategori> TblUrunKategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunPazar> TblUrunPazar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUrunStock> TblUrunStock { get; set; }
    }
}
