//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunStock
    {
        public int StokId { get; set; }
        public int UrunId { get; set; }
        public int BirimTipiId { get; set; }
        public double Miktar { get; set; }
    
        public virtual TblBirimTipleri TblBirimTipleri { get; set; }
        public virtual TblUrun TblUrun { get; set; }
    }
}
