//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwKategorikUrunler
    {
        public int UrunId { get; set; }
        public string UrunKategorisi { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsAtDiscount { get; set; }
        public Nullable<bool> IsExist { get; set; }
        public string img { get; set; }
        public Nullable<int> StokAdedi { get; set; }
        public Nullable<int> UrunNo { get; set; }
        public string Yol { get; set; }
        public double Fiyat { get; set; }
        public Nullable<bool> Indirim { get; set; }
        public int KdvOrani { get; set; }
        public int UrunFiyatDovizId { get; set; }
        public string DovizCinsi { get; set; }
        public string UrunKategoriAciklamasi { get; set; }
        public Nullable<int> KategoriId { get; set; }
    }
}
