//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwKisiKullaniciIletisim
    {
        public int KisiId { get; set; }
        public Nullable<int> AdresId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public long Tc { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Cinsiyet { get; set; }
        public Nullable<System.DateTime> KayıtTarihi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<bool> Silik { get; set; }
        public byte[] KayıtVersiyonu { get; set; }
        public int KullaniciId { get; set; }
        public string KullaniciAdi { get; set; }
        public string Sifre { get; set; }
        public Nullable<System.Guid> Guid { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
        public Nullable<System.DateTime> SonGirisTarihi { get; set; }
        public int AdreesTabloId { get; set; }
        public string Adres { get; set; }
        public string AdresBasligi { get; set; }
    }
}
