//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwKullaniciRol
    {
        public string KullaniciAdi { get; set; }
        public int KullaniciId { get; set; }
        public string Sifre { get; set; }
        public int KisiId { get; set; }
        public string Mesaj { get; set; }
        public Nullable<bool> Silik { get; set; }
        public Nullable<System.DateTime> SonGirisTarihi { get; set; }
        public byte[] KayitVersiyonu { get; set; }
        public Nullable<bool> Admin { get; set; }
        public Nullable<bool> Yetkili { get; set; }
        public int RolId { get; set; }
        public Nullable<bool> Ayarlar { get; set; }
        public Nullable<bool> Siparis { get; set; }
        public Nullable<bool> Tahsilat { get; set; }
        public Nullable<int> KullaniciTabloId { get; set; }
    }
}
