//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YeniData
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSepetDetay
    {
        public int SepetDetayId { get; set; }
        public int SepetId { get; set; }
        public int UrunId { get; set; }
        public System.DateTime UrunEklemeTarihi { get; set; }
        public int Adet { get; set; }
        public double BirimFiyat { get; set; }
        public double GuncelBirimFiyat { get; set; }
        public int KdvOrani { get; set; }
        public decimal GuncelKdvOrani { get; set; }
        public Nullable<decimal> GumcelDovizKuru { get; set; }
        public Nullable<double> IndirimOrani { get; set; }
        public int KuponId { get; set; }
        public Nullable<double> Miktar { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<double> AraToplam { get; set; }
    }
}
